### ISSUE TITLE
Add "info and acronyms" page

### ISSUE THREAD

**Issue by mscroggs** [mscroggs/fenics2021#3]
To include the meaning of:
- FEniCS
- FEniCSx
- DOLFIN
- DOLFINx
- FFC
- FFCx
- FIAT
- Basix
- UFL

Links to:
- FEniCS project
- DOLFINx tutorial
- DefElement

**Comment by jorgensd** [comment]
Add link to discourse, slack

**Comment by jorgensd** [comment]
PETSc
